from utilities.new_spherical_templates_generator import NewSphericalTemplatesGenerator

sphericalTemplateGenerator = NewSphericalTemplatesGenerator(8000, 'templates')
sphericalTemplateGenerator.generate_spheres()
